import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Header } from '@/components/layout/Header'
import { Footer } from '@/components/layout/Footer'
import { ChatbotFAB } from '@/components/layout/ChatbotFAB'

const sections = [
  {
    title: '1. General Information Only',
    body: 'The content on this website is provided for general informational purposes about ROMEIGH Multi-Enterprises and its services. It does not constitute professional legal, regulatory, or technical advice. For specific compliance questions, consult a qualified environmental professional or legal counsel.',
  },
  {
    title: '2. No Warranty',
    body: 'ROMEIGH makes no warranties, express or implied, regarding the accuracy, completeness, or suitability of the information on this website for any particular purpose. Regulatory requirements change over time; information presented here may not reflect the most current rules or amendments.',
  },
  {
    title: '3. Limitation of Liability',
    body: 'To the fullest extent permitted by Philippine law, ROMEIGH Multi-Enterprises shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use of, or reliance on, information provided on this website or through our chatbot assistant.',
  },
  {
    title: '4. Third-Party Links',
    body: 'This website may contain links to external websites. ROMEIGH is not responsible for the content, accuracy, or privacy practices of any third-party sites. Links are provided for convenience only and do not constitute endorsement.',
  },
  {
    title: '5. Regulatory Information',
    body: 'References to Philippine laws (RA 6969, RA 9275, RA 8749, DAO 2013-22, DAO 2021-08) are provided for informational context only. Always refer to the official DENR-EMB guidelines and current legislation for compliance purposes. ROMEIGH does not represent any government agency.',
  },
  {
    title: '6. AI Chatbot Disclaimer',
    body: 'This website includes an AI-powered chatbot assistant. Responses generated by the chatbot are for informational guidance only and may not be accurate, complete, or current. Do not rely on chatbot responses as legal or regulatory advice. Always verify information with a ROMEIGH representative.',
  },
  {
    title: '7. Governing Law',
    body: 'This disclaimer and your use of this website are governed by the laws of the Republic of the Philippines. Any disputes shall be subject to the jurisdiction of the appropriate Philippine courts.',
  },
]

const LegalDisclaimer: NextPage = () => {
  return (
    <>
      <Head>
        <title>Legal Disclaimer — ROMEIGH Multi-Enterprises</title>
        <meta name="description" content="Legal disclaimer for ROMEIGH Multi-Enterprises website." />
      </Head>

      <Header />

      <main>
        <section className="bg-hero-gradient py-16">
          <div className="max-w-site mx-auto px-6 lg:px-12 text-center">
            <span className="inline-block text-sky-400 text-[11px] font-bold tracking-[0.2em] uppercase mb-4">Legal</span>
            <h1 className="font-display font-extrabold text-white text-[clamp(2rem,4vw,3rem)] leading-tight">
              Legal Disclaimer
            </h1>
            <p className="text-white/50 text-sm mt-4">Last updated: January 1, 2024</p>
          </div>
        </section>

        <section className="bg-white py-20 border-t border-gray-100">
          <div className="max-w-2xl mx-auto px-6">
            <p className="text-gray-500 text-[16px] leading-[1.8] mb-10">
              Please read this disclaimer carefully before using the ROMEIGH Multi-Enterprises website.
              By accessing or using this website, you agree to be bound by these terms.
            </p>
            <div className="space-y-8">
              {sections.map(s => (
                <div key={s.title}>
                  <h2 className="font-display font-bold text-navy text-lg mb-2">{s.title}</h2>
                  <p className="text-gray-500 text-sm leading-relaxed">{s.body}</p>
                </div>
              ))}
            </div>
            <div className="mt-12 pt-8 border-t border-gray-100 text-center">
              <Link href="/" className="text-sky-600 hover:text-sky-700 text-sm font-medium transition-colors">
                ← Back to Homepage
              </Link>
            </div>
          </div>
        </section>
      </main>

      <Footer />
      <ChatbotFAB />
    </>
  )
}

export default LegalDisclaimer
